version: 4.1.0.{build}
branches:
  only:
    - master
    - dev
skip_tags: true
image: Visual Studio 2015
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
platform: Any CPU
configuration: Release
before_build:
- nuget restore src/Logikfabrik.Umbraco.Jet.sln
build:
  project: src/Logikfabrik.Umbraco.Jet.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
nuget:
  project_feed: true
  disable_publish_on_pr: true